In [1]:
import numpy as np

In [9]:
A = np.arange(1, 21).reshape(5, 4)
B = np.arange(1, 13).reshape(4, 3)

In [11]:
print(A)
print(B)
print(np.matmul(A, B))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 70  80  90]
 [158 184 210]
 [246 288 330]
 [334 392 450]
 [422 496 570]]


 (Sparse matrix-vector multiplication) What is the worst case time complexity (in Big O
notation) of multiplying a matrix A of dimension R n×n with a dense vector v ∈ R n ? What
if matrix A is sparse, denote the number of non-zero elements by nnz(A)? Write a python
function that takes a nonnegative integer n and outputs a sparse matrix A of size n − 1 × n,
such that for any x ∈ R n , Ax = [x 1 −x 2 ,...,x n−1 −x n ] T . Write a script that calls this function
and print the resulting A for n = 5. (Make sure you use the sparse matrix library in python
is scipy.sparse.)

In [26]:
n = 5
sparseMatrix = spareConstructor(np.zeros((n-1, n)))

In [27]:
def spareConstructor(sMatrix):
    maX = sMatrix.shape[0]
    maY = sMatrix.shape[1]
    for x in range(maX):
        sMatrix[x][x] = 1
        sMatrix[x][x+1] = -1
    return sMatrix


In [28]:
print(sparseMatrix)

[[ 1. -1.  0.  0.  0.]
 [ 0.  1. -1.  0.  0.]
 [ 0.  0.  1. -1.  0.]
 [ 0.  0.  0.  1. -1.]]


Question 4

In [29]:
def fac(n):
    if n == 1:
        return 1
    return n * fac(n -1)

In [30]:
fac(5)

120

Question 3

In [57]:
with open('training.txt', 'r') as data:
    lines = data.read().splitlines() 

In [58]:
#idea: use hashtable to store occurences of words, and build a priority queue of sorts using list to maintain top 20

In [105]:
occurences = {}
top20 = [('buffer', 0) for x in range(20)]
for x in range(len(lines)):
    currentLine = lines[x].split(' ')
    for y in range(len(currentLine)):
        try:
            occurences[currentLine[y]] += 1
            if occurences[currentLine[y]] > top20[19][1]:
                inn = False
                for x in range(20):
                    if top20[x][0] == currentLine[y]:
                        top20[x] = (top20[x][0], top20[x][1] + 1)
                        inn = True
                        break
                if (not inn):
                    top20[19] = (currentLine[y], occurences[currentLine[y]])
                    top20.sort(reverse = True, key=lambda el: el[1])
        except KeyError: 
            occurences[currentLine[y]] = 1
            if occurences[currentLine[y]] > top20[19][1]:
                top20[19] = (currentLine[y], occurences[currentLine[y]])
                top20.sort(reverse = True, key=lambda el: el[1])
    

In [111]:

top20.sort(reverse = True, key=lambda el: el[1])
for x in range(20):
    print(top20[x])

('the', 190806)
('of', 116447)
('and', 102422)
('to', 89251)
('a', 72558)
('in', 56026)
('i', 45308)
('that', 39378)
('he', 38160)
('it', 34361)
('was', 33834)
('his', 28771)
('â', 28051)
('with', 25151)
('as', 25032)
('for', 23788)
('you', 2666)
('is', 817)
('had', 538)
('her', 404)


In [112]:
lines[0]

'the main another curious and picturesque series of wall gardens are made by thin streams that slowly from and slip gently over smooth slopes from of sand and mud they carry a pair of sheets of soil an inch or two thick are formed one of them hanging down from the brow of the slope the other leaning up our national from the foot of it like and the soil being held together by the moisture plants growing in it along the rocky parts of the between lake where the streams flow fast over polished granite there are rows of gardens full of and other common plants of the neighborhood nicely arranged like and out in telling on the bare shining rock banks and au the way up the to the summit mountains wherever there is soil of any sort there is no lack of flowers however short the summer may be within eight or ten feet of a snow bank lingering beneath a shadow you may see their in september and hurrying up their brown on ground that has been free from snow only eight or ten days and likely to be c