In [1]:
import numpy as np

In [9]:
A = np.arange(1, 21).reshape(5, 4)
B = np.arange(1, 13).reshape(4, 3)

In [11]:
print(A)
print(B)
print(np.matmul(A, B))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 70  80  90]
 [158 184 210]
 [246 288 330]
 [334 392 450]
 [422 496 570]]
